---
title: "GraphTableCollection"
author: "Robert Petit"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
source("../../Code/include.R", local=TRUE)
WorkoutData = read_csv(here("Data/Workouts.csv"))

CURRENTWEEK = 3
```


``` {r BuildStats}
# Generates all of the stats

MilesCovered_Total <- WorkoutData %>% summarize(Covered = sum(FrodoMiles)) %>% pull(Covered)
MilesCovered_Weekly <- WorkoutData %>% filter(Week == CURRENTWEEK) %>% summarize(Covered = sum(FrodoMiles)) %>% pull(Covered)
MilesCovered_LastWeek <- WorkoutData %>% filter(Week == CURRENTWEEK-1) %>% summarize(Covered = sum(FrodoMiles)) %>% pull(Covered)

WD_Stats <- WorkoutData %>% Stats_PerPerson(CURRENTWEEK)

WeeklyFrodo <- WD_Stats %>% arrange(desc(WeeklyDistance)) %>% head(1)
WeeklySam <- WD_Stats %>% filter(Name != WeeklyFrodo$Name) %>% arrange(desc(WeeklyTime)) %>% head(1)
```

# Critical Stats
Total miles so far is `r MilesCovered_Total`. Total miles this week is `r MilesCovered_Weekly`. This week's Frodo is `r WeeklyFrodo$Name` with `r WeeklyFrodo$WeeklyDistance` FrodoMiles. This week's Sam is `r WeeklySam$Name` with `r WeeklySam$WeeklyTime / 60` minutes moving.

# Leaderboards
```{r FMLeader}
WD_Stats %>%
  select(Name, TotalDistance) %>%
  arrange(desc(TotalDistance)) %>%
  kable(col.names = c("Names", "Frodo Miles"),
        caption = "Total Frodo Miles")
```

```{r FMWeeklyLeader}
WD_Stats %>%
  select(Name, WeeklyDistance) %>%
  filter(WeeklyDistance>0) %>%
  arrange(desc(WeeklyDistance)) %>%
  kable(col.names = c("Names", "Frodo Miles"),
        caption = "Weekly Frodo Miles")
```

# Graphs

```{r MilesByDay_Weekly}
WorkoutData %>%
  filter(Week==CURRENTWEEK) %>%
  group_by(Day) %>%
  summarize(DayFM = sum(FrodoMiles)) %>%
  ggplot(mapping=aes(
    x = factor(Day, levels=c("Su", "M", "Tu", "W", "Tr", "F", "Sa")),
    y = DayFM,
    fill=Day)) +
  geom_col() +
  scale_fill_brewer(type="qual", palette=6) +
  labs(
    title = "Group Miles By Day, This Week",
    x="Day",
    y="Frodo Miles"
  )
```

```{r PerPersonChange} 
WD_Stats %>%
  # We add 0.01 to ensure that people with no change are visible
  mutate(NetChange = (WeeklyDistance - LagWeeklyDistance)+0.01) %>%
  ggplot(mapping = aes(
    x=reorder(Name, NetChange), 
    y=NetChange,
    fill=reorder(Name, NetChange))) +
  geom_col() +
  scale_fill_brewer(type='qual', palette=6) +
  theme(legend.position="none") +
  labs(title = "Weekly Change in FrodoMiles",
       x="Name",
       y="Change Since Last Week")

```